### ISSUE TITLE
[refactor] 비교 분석 레포트 - 소비 레포트 top3 조회 api 수정

### ISSUE THREAD

**Issue by m3k0813** [BudgetBuddiesTeam/BackEnd#160]
## 💡Description
> 소비가 없어도 소비 건수가 합산되는 문제 발견

## ✅ To Do List
- [x] 소비 레포트 수정

## Etc
> etc

**Comment by SoulTree-Lovers** [comment]
결국 문제를 발견하셨나요 .. !

**Comment by m3k0813** [comment]
> 결국 문제를 발견하셨나요 .. !

기존에 Mock 데이터가 너무 많아서 찾기 힘들었는데 consumptionGoal이랑 expense가 안맞아서 생긴 문제로 판단했습니다!
